name: Security Scan

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - actin_test
  workflow_dispatch: {}

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo "Adding Trivy to PATH"
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy vulnerability scan
        run: |
          trivy fs . --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed --scanners vuln
  
  
  dependabot-check:
    name: Dependency Updates
    needs: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependabot Alerts
        uses: advanced-security/dependabot-alerts-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
